# Generated by Django 4.0.4 on 2022-04-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correctAnwer',
            new_name='correctAnswer',
        ),
    ]
